server:
  port: 8080

spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #配置枚举
  type-enums-package: com.yishang.yspay.bean.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
